[package]
name = "libmilkyway_derive"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "A procedural macros for libmilkyway"

[dependencies]
syn = "2.0.68"
quote = "1.0.36"
proc-macro2 = "1.0.86"

[lib]
proc-macro = true
