[package]
name = "ping"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
libmilkyway = {path = "../../libmilkyway"}
# External dependencies
colored = "2.1.0"
log = "0.4.22"