[package]
name = "milkywaycli"
version = "0.1.0"
edition = "2021"

[dependencies]
libmilkyway = {path = "../libmilkyway"}
libmilkyway_derive = { path = "../libmilkyway_derive"}
# External crates
colored = "2.1.0"
yaml-rust2 = "0.8.1"
